export const FETCH_MOVIES_INITIATED = "FETCH_MOVIES_INITIATED";
export const FETCH_MOVIES_FAILED = "FETCH_MOVIES_FAILED";
export const FETCH_MOVIES_SUCCEEDED = "FETCH_MOVIES_SUCCEEDED";
export const FETCH_MOVIE_INITIATED = 'FETCH_MOVIE_INITIATED';
export const FETCH_MOVIE_FAILED = "FETCH_MOVIE_FAILED";
export const FETCH_MOVIE_SUCCEEDED = "FETCH_MOVIE_SUCCEEDED";
export const MOVIE_CLICKED = "MOVIE_CLICKED";